spring:
  application:
    name: zuul-service
  ##启用retry机制
  cloud:
    loadbalancer:
      retry:
        enabled: true
            
server:
  context-path: /
  port: 5002
  
eureka: 
  client:
    service-url:
      defaultZone: http://eureka1:8001/eureka
      
zuul:
  routes:
    api-order:
      path: /order-service/**
      service-id: order-service  
    api-user:
      path: /user-service/**
      service-id: user-service      



##设置断路器的超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 30000    

##全局请求的负载均衡和重试配置
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 3000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 2  

##全局的代理配置
feign:
  hystrix: 
    enabled: true
  compression:
    request:
      min-request-size: 2048
      mime-types:
        - text/html, application/xml, application/json    
   
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      